### ISSUE TITLE
How to replace matched abbreviations?

### ISSUE THREAD

**Issue by wzyboy** [crispgm/cmp-beancount#2]
Thanks for the plugin!

I'm migrating from deoplete to nvim-cmp and have a question regarding the abbreviation match capability of this plugin.

In my previous setup of deoplete + vim-beancount + supertab, there is abbreviation-based auto-completion. For example:

```
I:E:C<Tab>
```

turns into

```
Income:Employment:Company
```

However, with nvim-cmp + cmp-beancount, the same key sequence turns the text into:

```
I:E:Income:Employment:Company
```

Note that only `C` got replaced, but not the entire `I:E:C` string.

I tried to debug if this is the issue with my nvim-cmp mapping. But even with the exact same mapping as [yours](https://github.com/crispgm/dotfiles/blob/8ce2fbbf92d910e8dc55a2650f23a1a657c3379a/rc/config/nvim/lua/plugins/cmp.lua#L4-L13), I cannot get the abbrevation replacement working.

Could you shed some light on this? Thanks.

**Comment by crispgm** [comment]
I noticed this issue as well. I have no idea but I think I am gonna figure this out this weekends though.

**Comment by crispgm** [comment]
> I noticed this issue as well. I have no idea but I think I am gonna figure this out this weekends though.

It's fixed lol, it works good for me. You may update later :)

**Comment by wzyboy** [comment]
Thanks! It works for me as well!
